package com.thrifleganger.alexa.scene.constants;

public enum PathState {

    SCENE_INVOCATION_STARTED,
    SCENE_INVOCATION_COMPLETE,
    AWAITING_MORE_RESULTS_OR_MORE_DETAILS,
    AWAITING_MORE_DETAILS,
    AWAITING_MORE_DETAILS_FOR_SINGLE_RESULT,
    UNDETERMINED;
}
